starting worker pid=17632 on localhost:11420 at 13:37:47.055
starting worker pid=6120 on localhost:11420 at 13:37:47.318
starting worker pid=3552 on localhost:11420 at 13:37:47.603
starting worker pid=3640 on localhost:11420 at 13:37:47.882
starting worker pid=6452 on localhost:11420 at 13:37:48.173
starting worker pid=19252 on localhost:11420 at 13:37:48.474
starting worker pid=18504 on localhost:11420 at 13:37:48.875
starting worker pid=17792 on localhost:11420 at 13:37:49.188
starting worker pid=17104 on localhost:11420 at 13:37:49.535
starting worker pid=15924 on localhost:11420 at 13:37:49.811
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
ze(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
